<template>
  <div ref="rootEl" class="s-c s-receipt-doc" aria-hidden="true">
    <header class="s-receipt-doc__header">
      <img v-if="storeLogoUrl" :src="storeLogoUrl" alt="" class="s-receipt-doc__logo" />
      <h1 class="s-receipt-doc__title">{{ businessName || 'Store' }}</h1>
      <p v-if="branchName" class="s-receipt-doc__sub">{{ branchName }}</p>
    </header>

    <section class="s-receipt-doc__section">
      <div class="s-receipt-doc__split">
        <div>
          <p class="s-receipt-doc__label">Receipt</p>
          <p class="s-receipt-doc__value s-receipt-doc__value--strong">
            {{ receipt.receiptNumber }}
          </p>
        </div>
        <div class="s-receipt-doc__end">
          <p class="s-receipt-doc__label">Date</p>
          <p class="s-receipt-doc__value">{{ dateLabel }}</p>
        </div>
      </div>
      <div class="s-receipt-doc__party">
        <p class="s-receipt-doc__label">Customer</p>
        <p class="s-receipt-doc__value s-receipt-doc__value--strong">{{ receipt.customerName }}</p>
        <p v-if="receipt.customerPhone" class="s-receipt-doc__fine">
          {{ receipt.customerPhone }}
        </p>
      </div>
    </section>

    <section class="s-receipt-doc__section">
      <table class="s-receipt-doc__table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col" class="s-receipt-doc__center">Qty</th>
            <th scope="col" class="s-receipt-doc__num">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(item, i) in receipt.items || []" :key="i">
            <td class="s-receipt-doc__item-name">{{ item.itemName }}</td>
            <td class="s-receipt-doc__center">{{ item.quantity }}</td>
            <td class="s-receipt-doc__num s-receipt-doc__strong">
              {{ formatCurrency(item.price * item.quantity) }}
            </td>
          </tr>
        </tbody>
      </table>
      <div class="s-receipt-doc__totals">
        <div class="s-receipt-doc__grand s-receipt-doc__grand--plain">
          <span>Total</span>
          <span>{{ formatCurrency(receipt.total) }}</span>
        </div>
      </div>
    </section>

    <footer class="s-receipt-doc__footer">
      <p>Thank you for your business</p>
      <p class="s-receipt-doc__fine">Generated by storvv</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Receipt } from '~/stores/receipts'

const props = defineProps<{
  receipt: Receipt
  businessName?: string
  branchName?: string
  /** @deprecated use businessName */
  storeName?: string
  storeLogoUrl?: string
}>()

const rootEl = ref<HTMLElement | null>(null)
const { formatCurrency } = usePreferences()

const businessName = computed(
  () => props.businessName?.trim() || props.storeName?.trim() || 'Store'
)
const branchName = computed(() => props.branchName?.trim() || '')

const dateLabel = computed(() => {
  const d = props.receipt.date as { toDate?: () => Date } | Date | string
  const date =
    d && typeof d === 'object' && 'toDate' in d && d.toDate ? d.toDate() : new Date(d as string)
  return date.toLocaleString()
})

defineExpose({
  getElement: () => rootEl.value,
})
</script>
