import type { Component } from 'vue'
import {
  Apple,
  Baby,
  BedDouble,
  Bike,
  Blocks,
  BookOpen,
  Boxes,
  BrickWall,
  Briefcase,
  Brush,
  Cable,
  Camera,
  CandyCane,
  CarFront,
  Cog,
  Coffee,
  CookingPot,
  Cpu,
  Croissant,
  CupSoda,
  Droplets,
  Dumbbell,
  Factory,
  Fish,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Guitar,
  Handbag,
  Headphones,
  HeartPulse,
  Lamp,
  Laptop,
  Milk,
  Package,
  PaintBucket,
  Palette,
  Paperclip,
  PawPrint,
  PencilLine,
  Pill,
  PlugZap,
  Printer,
  Refrigerator,
  Router,
  Scissors,
  Shapes,
  Shirt,
  ShoppingBasket,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Spool,
  SprayCan,
  Sprout,
  Stethoscope,
  SunMedium,
  Tablet,
  Tent,
  Tractor,
  Tv,
  UtensilsCrossed,
  Watch,
  Wine,
  Wrench,
} from '@lucide/vue'
import { resolveCategoryKind } from '~/utils/category-kinds'

const KIND_ICONS: Record<string, Component> = {
  phones: Smartphone,
  computers: Laptop,
  tablets: Tablet,
  wearables: Watch,
  audio: Headphones,
  tv: Tv,
  cameras: Camera,
  gaming: Gamepad2,
  accessories: Cable,
  networking: Router,
  solar: SunMedium,
  electronics: Cpu,
  appliances: Refrigerator,
  furniture: Sofa,
  kitchen: CookingPot,
  decor: Lamp,
  bedding: BedDouble,
  cleaning: Brush,
  clothing: Shirt,
  shoes: Footprints,
  bags: Handbag,
  jewelry: Gem,
  fragrance: SprayCan,
  beauty: Sparkles,
  hair: Scissors,
  fabrics: Spool,
  eyewear: Glasses,
  food: ShoppingBasket,
  produce: Apple,
  meat: Fish,
  bakery: Croissant,
  snacks: CandyCane,
  dairy: Milk,
  drinks: CupSoda,
  alcohol: Wine,
  coffee: Coffee,
  meals: UtensilsCrossed,
  frozen: Snowflake,
  pharmacy: Pill,
  medical: Stethoscope,
  wellness: HeartPulse,
  building: BrickWall,
  tools: Wrench,
  electrical: PlugZap,
  plumbing: Droplets,
  paint: PaintBucket,
  industrial: Factory,
  vehicles: CarFront,
  automotive: Cog,
  motorcycles: Bike,
  fuel: Fuel,
  office: Paperclip,
  books: BookOpen,
  stationery: PencilLine,
  printing: Printer,
  school: GraduationCap,
  baby: Baby,
  toys: Blocks,
  sports: Dumbbell,
  outdoor: Tent,
  music: Guitar,
  arts: Palette,
  gifts: Gift,
  agriculture: Tractor,
  pets: PawPrint,
  garden: Sprout,
  general: Package,
  wholesale: Boxes,
  services: Briefcase,
  other: Shapes,
}

export function categoryKindIcon(id: string | null | undefined): Component {
  return KIND_ICONS[String(id || '')] ?? Package
}

/** Icon for an inventory category: its kind, or a guess from its name when the kind is vague. */
export function folderKindIcon(
  folder: { type?: string; name?: string } | null | undefined,
  parentName?: string
): Component {
  return categoryKindIcon(resolveCategoryKind(folder?.type, folder?.name, parentName))
}
