export async function generatePaymentReminderImage(params: {
 storeName: string
 customerName: string
 balanceDue: string
}): Promise<Blob> {
 const width = 640
 const height = 360
 const canvas = document.createElement('canvas')
 canvas.width = width
 canvas.height = height
 const ctx = canvas.getContext('2d')
 if (!ctx) throw new Error('Canvas not supported')

 ctx.fillStyle = '#ffffff'
 ctx.fillRect(0, 0, width, height)
 ctx.strokeStyle = '#e5e7eb'
 ctx.lineWidth = 2
 ctx.strokeRect(16, 16, width - 32, height - 32)

 ctx.fillStyle = '#111827'
 ctx.font = 'bold 22px system-ui, sans-serif'
 ctx.fillText(params.storeName, 40, 56)

 ctx.fillStyle = '#6b7280'
 ctx.font = '12px system-ui, sans-serif'
 ctx.fillText('PAYMENT REMINDER', 40, 80)

 ctx.fillStyle = '#374151'
 ctx.font = '16px system-ui, sans-serif'
 ctx.fillText(`Hi ${params.customerName},`, 40, 120)

 ctx.fillStyle = '#111827'
 ctx.font = 'bold 28px system-ui, sans-serif'
 ctx.fillText(params.balanceDue, 40, 170)

 ctx.fillStyle = '#6b7280'
 ctx.font = '14px system-ui, sans-serif'
 const line = 'Outstanding balance. Please arrange payment at your earliest convenience.'
 wrapText(ctx, line, 40, 210, width - 80, 20)

 ctx.fillStyle = '#9ca3af'
 ctx.font = '11px system-ui, sans-serif'
 ctx.fillText('Generated by Storvv', 40, height - 36)

 return await new Promise((resolve, reject) => {
 canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('Failed to create image'))), 'image/png', 0.92)
 })
}

function wrapText(
 ctx: CanvasRenderingContext2D,
 text: string,
 x: number,
 y: number,
 maxWidth: number,
 lineHeight: number
) {
 const words = text.split(' ')
 let line = ''
 let cy = y
 for (const word of words) {
 const test = line ? `${line} ${word}` : word
 if (ctx.measureText(test).width > maxWidth && line) {
 ctx.fillText(line, x, cy)
 line = word
 cy += lineHeight
 } else {
 line = test
 }
 }
 if (line) ctx.fillText(line, x, cy)
}
