/**
 * Major cities per onboarding region code (matches `regions` in usePreferences.ts).
 */
export const citiesByRegion: Record<string, readonly string[]> = {
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Columbus',
    'Charlotte',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Boston',
    'Nashville',
    'Detroit',
    'Portland',
    'Las Vegas',
    'Miami',
    'Atlanta',
  ],
  NG: [
    'Lagos',
    'Abuja',
    'Kano',
    'Ibadan',
    'Port Harcourt',
    'Benin City',
    'Kaduna',
    'Enugu',
    'Aba',
    'Onitsha',
    'Jos',
    'Ilorin',
    'Warri',
    'Calabar',
    'Uyo',
    'Abeokuta',
    'Owerri',
    'Sokoto',
    'Maiduguri',
    'Akure',
  ],
  GB: [
    'London',
    'Birmingham',
    'Manchester',
    'Glasgow',
    'Leeds',
    'Liverpool',
    'Sheffield',
    'Edinburgh',
    'Bristol',
    'Leicester',
    'Coventry',
    'Nottingham',
    'Newcastle upon Tyne',
    'Southampton',
    'Brighton',
    'Cardiff',
    'Belfast',
  ],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
    'London',
    'Halifax',
    'Victoria',
    'Saskatoon',
    'Regina',
  ],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Hobart',
    'Geelong',
    'Townsville',
    'Cairns',
    'Darwin',
  ],
  EU: [
    'Paris',
    'Berlin',
    'Madrid',
    'Rome',
    'Amsterdam',
    'Brussels',
    'Vienna',
    'Dublin',
    'Lisbon',
    'Prague',
    'Warsaw',
    'Stockholm',
    'Copenhagen',
    'Helsinki',
    'Athens',
    'Budapest',
    'Zurich',
    'Munich',
    'Barcelona',
    'Milan',
  ],
  GH: [
    'Accra',
    'Kumasi',
    'Tamale',
    'Takoradi',
    'Cape Coast',
    'Tema',
    'Sunyani',
    'Ho',
    'Koforidua',
    'Wa',
    'Bolgatanga',
  ],
  KE: [
    'Nairobi',
    'Mombasa',
    'Kisumu',
    'Nakuru',
    'Eldoret',
    'Thika',
    'Malindi',
    'Kitale',
    'Garissa',
    'Nyeri',
  ],
  ZA: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Polokwane',
    'Nelspruit',
    'Kimberley',
  ],
  JP: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Hiroshima',
    'Sendai',
  ],
  CN: [
    'Shanghai',
    'Beijing',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
    'Xi\'an',
    'Nanjing',
    'Tianjin',
    'Chongqing',
    'Suzhou',
  ],
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
  ],
}

export function getCitiesForRegion(regionCode: string): string[] {
  const list = citiesByRegion[regionCode]
  if (!list?.length) return []
  return [...list].sort((a, b) => a.localeCompare(b))
}

export function isCityInRegion(city: string, regionCode: string): boolean {
  const normalized = city.trim().toLowerCase()
  if (!normalized) return false
  return getCitiesForRegion(regionCode).some((c) => c.toLowerCase() === normalized)
}
