import type { SocialEvent, SocialLead } from '~/types/social-sales'

const now = new Date()
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000)

/** Demo leads for Phase 1 UI (replaced by Firestore in Phase 3). */
export function createMockSocialLeads(storeId: string): SocialLead[] {
  return [
    {
      id: 'lead-001',
      storeId,
      customerName: 'Ada Okonkwo',
      customerPhone: '+234 803 111 2233',
      whatsappNumber: '+234 803 111 2233',
      platform: 'whatsapp',
      productName: 'iPhone 15 Pro 256GB',
      estimatedValue: 985000,
      status: 'negotiating',
      assignedTo: 'staff-1',
      assignedToName: 'Tunde Adeyemi',
      notes: 'Asked about colour options. Prefers natural titanium.',
      source: 'whatsapp',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-002',
      storeId,
      customerId: 'cust-demo-2',
      customerName: 'Chioma Eze',
      customerPhone: '+234 701 555 8899',
      instagramUsername: '@chioma.gadgets',
      platform: 'instagram',
      productName: 'MacBook Air M2',
      estimatedValue: 1150000,
      status: 'payment_pending',
      assignedTo: 'staff-2',
      assignedToName: 'Funke Bello',
      notes: 'Deposit received. Customer collecting Friday.',
      source: 'instagram',
      createdAt: daysAgo(8),
      updatedAt: daysAgo(2),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-003',
      storeId,
      customerName: 'James Walker',
      platform: 'walk_in',
      productName: 'Samsung Galaxy S24 Ultra',
      estimatedValue: 820000,
      wonRevenue: 795000,
      status: 'won',
      assignedTo: 'staff-1',
      assignedToName: 'Tunde Adeyemi',
      source: 'walk_in',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(10),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-004',
      storeId,
      customerName: 'Fatima Yusuf',
      whatsappNumber: '+234 909 444 7788',
      platform: 'whatsapp',
      productName: 'AirPods Pro 2',
      estimatedValue: 185000,
      status: 'contacted',
      assignedTo: 'staff-2',
      assignedToName: 'Funke Bello',
      source: 'whatsapp',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-005',
      storeId,
      customerName: 'Emeka Nwosu',
      instagramUsername: '@emeka.tech',
      platform: 'instagram',
      productName: 'iPad Pro 11"',
      estimatedValue: 650000,
      status: 'lost',
      assignedTo: 'staff-1',
      assignedToName: 'Tunde Adeyemi',
      notes: 'Bought elsewhere — price mismatch.',
      source: 'instagram',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(15),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-006',
      storeId,
      customerName: 'Sarah Mensah',
      platform: 'referral',
      productName: 'Apple Watch Series 9',
      estimatedValue: 420000,
      status: 'new',
      source: 'referral',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-007',
      storeId,
      customerName: 'David Kim',
      whatsappNumber: '+234 802 333 9900',
      platform: 'whatsapp',
      productName: 'PlayStation 5 Slim',
      estimatedValue: 580000,
      wonRevenue: 575000,
      status: 'won',
      assignedTo: 'staff-2',
      assignedToName: 'Funke Bello',
      source: 'whatsapp',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(25),
      createdBy: 'demo-owner',
    },
    {
      id: 'lead-008',
      storeId,
      customerName: 'Amina Hassan',
      instagramUsername: '@amina.style',
      platform: 'instagram',
      productName: 'iPhone 14 128GB',
      estimatedValue: 620000,
      wonRevenue: 610000,
      status: 'won',
      assignedTo: 'staff-1',
      assignedToName: 'Tunde Adeyemi',
      source: 'instagram',
      createdAt: daysAgo(12),
      updatedAt: daysAgo(9),
      createdBy: 'demo-owner',
    },
  ]
}

export function createMockSocialEvents(): SocialEvent[] {
  return [
    {
      id: 'evt-001',
      leadId: 'lead-001',
      type: 'created',
      description: 'Lead created from WhatsApp enquiry.',
      createdBy: 'demo-owner',
      createdByName: 'Store owner',
      timestamp: daysAgo(5),
    },
    {
      id: 'evt-002',
      leadId: 'lead-001',
      type: 'note',
      description: 'Asked about iPhone 15 Pro — natural titanium preferred.',
      createdBy: 'staff-1',
      createdByName: 'Tunde Adeyemi',
      timestamp: daysAgo(4),
    },
    {
      id: 'evt-003',
      leadId: 'lead-001',
      type: 'status_change',
      description: 'Status changed to Negotiating.',
      createdBy: 'staff-1',
      createdByName: 'Tunde Adeyemi',
      timestamp: daysAgo(1),
    },
    {
      id: 'evt-004',
      leadId: 'lead-002',
      type: 'created',
      description: 'Lead created from Instagram DM.',
      createdBy: 'demo-owner',
      createdByName: 'Store owner',
      timestamp: daysAgo(8),
    },
    {
      id: 'evt-005',
      leadId: 'lead-002',
      type: 'note',
      description: 'Deposit received — customer collecting Friday.',
      createdBy: 'staff-2',
      createdByName: 'Funke Bello',
      timestamp: daysAgo(2),
    },
    {
      id: 'evt-006',
      leadId: 'lead-002',
      type: 'status_change',
      description: 'Status changed to Payment Pending.',
      createdBy: 'staff-2',
      createdByName: 'Funke Bello',
      timestamp: daysAgo(2),
    },
    {
      id: 'evt-007',
      leadId: 'lead-003',
      type: 'converted_to_sale',
      description: 'Converted to sale — receipt pending link (demo).',
      createdBy: 'staff-1',
      createdByName: 'Tunde Adeyemi',
      timestamp: daysAgo(10),
    },
  ]
}
